### ISSUE TITLE
Duplicated hiragana

### ISSUE THREAD

**Issue by hsiehshun** [mirigana/mirigana#15]
Not all tokens has the form <kana+kanji+kana>, for example: 「間に合う」

In the function `renderRuby` ([here](https://github.com/mirigana/mirigana/blob/develop/src/content_scripts/common.js#L62)), `smashed` may also have hiragana inside, which would caused duplicated hiragana.

<img width="574" alt="Screen Shot 2021-09-14 at 3 07 51 AM" src="https://user-images.githubusercontent.com/82684594/133142186-9adfeef0-6fdc-4244-90b4-6d8eb5f5c259.png">

**Comment by larvata** [comment]
Fixed in version 1.1.0
Thanks for reporting.
