### ISSUE TITLE
[Suggestion] Ignore tweets written in Simplified/Traditional Chinese

### ISSUE THREAD

**Issue by Yesterday17** [mirigana/mirigana#4]
Maybe you can ignore tweets with no kana in it. (But it may be not so accurate. Further investigation is needed.)

**Comment by larvata** [comment]
It is not easy to find a solution by implementing an algorithm myself.

At this time I just use the lang flag from the tweet metadata.
I think it will be finally fixed automatically by the time twitter improves the accuracy of their language detect algorithm.

**Comment by vlzx** [comment]
How about [languagedetect](https://www.npmjs.com/package/languagedetect)?
